package resumes

import (
	"database/sql/driver"
	"encoding/json"
	"errors"
	"time"

	"github.com/google/uuid"
)

// ResumeContent represents the structured resume content generated by LLM.
// This is stored as JSONB in the database and parsed from LLM JSON responses.
// NOTE: JSON tags are intentional here — this type serves as both the DB serialization
// format (via ResumeContentDB.Value/Scan) and the LLM response parsing target.
// API responses use separate DTOs in dto.go with their own json tags.
type ResumeContent struct {
	Summary            string              `json:"summary"`
	Skills             []string            `json:"skills"`
	Experience         []ExperienceEntry   `json:"experience"`
	Projects           []ProjectEntry      `json:"projects"`
	Education          []EducationEntry    `json:"education"`
	Certifications     []string            `json:"certifications"`
	Languages          []LanguageEntry     `json:"languages"`
	Links              []LinkEntry         `json:"links"`
}

// ExperienceEntry represents a work experience entry in the structured resume.
type ExperienceEntry struct {
	Title        string   `json:"title"`
	Company      string   `json:"company"`
	Location     string   `json:"location"`
	StartDate    string   `json:"start_date"`
	EndDate      string   `json:"end_date"`
	Description  string   `json:"description"`
	SkillsUsed   []string `json:"skills_used"`
	Highlights   []string `json:"highlights"`
}

// ProjectEntry represents a project in the structured resume.
type ProjectEntry struct {
	Name         string   `json:"name"`
	Description  string   `json:"description"`
	Technologies []string `json:"technologies"`
	Link         string   `json:"link,omitempty"`
	StartDate    string   `json:"start_date,omitempty"`
	EndDate      string   `json:"end_date,omitempty"`
}

// EducationEntry represents an education entry in the structured resume.
type EducationEntry struct {
	Institution string   `json:"institution"`
	Degree      string   `json:"degree"`
	Field       string   `json:"field"`
	StartDate   string   `json:"start_date"`
	EndDate     string   `json:"end_date"`
	GPA         string   `json:"gpa,omitempty"`
	Honors      []string `json:"honors,omitempty"`
}

// LanguageEntry represents a language proficiency entry.
type LanguageEntry struct {
	Language    string `json:"language"`
	Proficiency string `json:"proficiency"` // native, fluent, professional, basic
}

// LinkEntry represents a link (GitHub, LinkedIn, portfolio, etc.)
type LinkEntry struct {
	Type  string `json:"type"` // github, linkedin, portfolio, website
	URL   string `json:"url"`
	Label string `json:"label,omitempty"`
}

// ResumeContentDB wraps ResumeContent for database driver compatibility.
type ResumeContentDB ResumeContent

// Value implements driver.Valuer for database storage.
func (r ResumeContentDB) Value() (driver.Value, error) {
	return json.Marshal(r)
}

// Scan implements sql.Scanner for database retrieval.
func (r *ResumeContentDB) Scan(value interface{}) error {
	if value == nil {
		*r = ResumeContentDB{}
		return nil
	}
	bytes, ok := value.([]byte)
	if !ok {
		return errors.New("type assertion to []byte failed")
	}
	return json.Unmarshal(bytes, r)
}

// Resume represents a resume version.
type Resume struct {
	ID                  uuid.UUID
	Name                string
	Specialization      string
	TemplatePath        string
	FocusSkills         []string
	HighlightExperience []uuid.UUID
	Content             ResumeContentDB     // Structured resume content (JSONB)
	PdfKey              *string
	Version             int32
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

// NewResume creates a new Resume with default values.
func NewResume(name, specialization, templatePath string, focusSkills []string) *Resume {
	now := time.Now().UTC()
	return &Resume{
		ID:                uuid.New(),
		Name:              name,
		Specialization:    specialization,
		TemplatePath:      templatePath,
		FocusSkills:       focusSkills,
		Content:           ResumeContentDB{}, // Empty content
		Version:           1,
		CreatedAt:         now,
		UpdatedAt:         now,
	}
}

// ResumeVersion represents a versioned snapshot of resume content.
type ResumeVersion struct {
	ID        uuid.UUID
	ResumeID  uuid.UUID
	Content   ResumeContentDB
	Version   int32
	PdfKey    *string
	CreatedAt time.Time
}

// CoverLetter represents a generated cover letter.
type CoverLetter struct {
	ID        uuid.UUID
	JobID     *uuid.UUID
	ResumeID  *uuid.UUID
	Content   string // Can be plain text or JSON for structured content
	PdfKey    *string
	WordCount *int
	Version   int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

// NewCoverLetter creates a new CoverLetter with default values.
func NewCoverLetter(content string) *CoverLetter {
	now := time.Now().UTC()
	return &CoverLetter{
		ID:        uuid.New(),
		Content:   content,
		Version:   1,
		CreatedAt: now,
		UpdatedAt: now,
	}
}

// Domain errors for resumes.
var (
	ErrInvalidInput    = errors.New("invalid input")
	ErrNotFound        = errors.New("resume not found")
	ErrNoContent       = errors.New("resume has no content")
	ErrVersionConflict = errors.New("version conflict — resume was modified by another process")
)