package resumes

import (
	"database/sql/driver"
	"encoding/json"
	"errors"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

// ResumeContent represents the structured resume content generated by LLM.
// This is stored as JSONB in the database and parsed from LLM JSON responses.
// NOTE: JSON tags are intentional here — this type serves as both the DB serialization
// format (via ResumeContentDB.Value/Scan) and the LLM response parsing target.
// API responses use separate DTOs in dto.go with their own json tags.
type ResumeContent struct {
	Summary        string            `json:"summary"`
	Skills         []string          `json:"skills"`
	Experience     []ExperienceEntry `json:"experience"`
	Projects       []ProjectEntry    `json:"projects"`
	Education      []EducationEntry  `json:"education"`
	Certifications []string          `json:"certifications"`
	Languages      []LanguageEntry   `json:"languages"`
	Links          []LinkEntry       `json:"links"`
}

// ExperienceEntry represents a work experience entry in the structured resume.
type ExperienceEntry struct {
	Title       string   `json:"title"`
	Company     string   `json:"company"`
	Location    string   `json:"location"`
	StartDate   string   `json:"start_date"`
	EndDate     string   `json:"end_date"`
	Description string   `json:"description"`
	SkillsUsed  []string `json:"skills_used"`
	Highlights  []string `json:"highlights"`
}

// ProjectEntry represents a project in the structured resume.
type ProjectEntry struct {
	Name         string   `json:"name"`
	Description  string   `json:"description"`
	Technologies []string `json:"technologies"`
	Link         string   `json:"link,omitempty"`
	StartDate    string   `json:"start_date,omitempty"`
	EndDate      string   `json:"end_date,omitempty"`
}

// EducationEntry represents an education entry in the structured resume.
type EducationEntry struct {
	Institution string   `json:"institution"`
	Degree      string   `json:"degree"`
	Field       string   `json:"field"`
	StartDate   string   `json:"start_date"`
	EndDate     string   `json:"end_date"`
	GPA         string   `json:"gpa,omitempty"`
	Honors      []string `json:"honors,omitempty"`
}

// LanguageEntry represents a language proficiency entry.
type LanguageEntry struct {
	Language    string `json:"language"`
	Proficiency string `json:"proficiency"` // native, fluent, professional, basic
}

// LinkEntry represents a link (GitHub, LinkedIn, portfolio, etc.)
type LinkEntry struct {
	Type  string `json:"type"` // github, linkedin, portfolio, website
	URL   string `json:"url"`
	Label string `json:"label,omitempty"`
}

// ResumeContentDB wraps ResumeContent for database driver compatibility.
type ResumeContentDB ResumeContent

// Value implements driver.Valuer for database storage.
func (r ResumeContentDB) Value() (driver.Value, error) {
	return json.Marshal(r)
}

// Scan implements sql.Scanner for database retrieval.
func (r *ResumeContentDB) Scan(value interface{}) error {
	if value == nil {
		*r = ResumeContentDB{}
		return nil
	}
	bytes, ok := value.([]byte)
	if !ok {
		return errors.New("type assertion to []byte failed")
	}
	return json.Unmarshal(bytes, r)
}

// StringSliceDB wraps []string for JSONB database storage.
// Used for columns like strengths/gaps that are JSONB arrays in PostgreSQL.
type StringSliceDB []string

// Value implements driver.Valuer for database storage.
func (s StringSliceDB) Value() (driver.Value, error) {
	if s == nil {
		return nil, nil
	}
	return json.Marshal(s)
}

// Scan implements sql.Scanner for database retrieval.
func (s *StringSliceDB) Scan(value interface{}) error {
	if value == nil {
		*s = nil
		return nil
	}
	bytes, ok := value.([]byte)
	if !ok {
		return errors.New("type assertion to []byte failed")
	}
	return json.Unmarshal(bytes, s)
}

// Resume represents a resume version.
type Resume struct {
	ID                  uuid.UUID       `db:"id"`
	Name                string          `db:"name"`
	Specialization      string          `db:"specialization"`
	TemplatePath        string          `db:"template_path"`
	FocusSkills         []string        `db:"focus_skills"`
	HighlightExperience pq.StringArray  `db:"highlight_experience"`
	Content             ResumeContentDB `db:"content"` // Structured resume content (JSONB)
	PdfKey              *string         `db:"pdf_key"`
	Version             int32           `db:"version"`
	CreatedAt           time.Time       `db:"created_at"`
	UpdatedAt           time.Time       `db:"updated_at"`
}

// NewResume creates a new Resume with default values.
func NewResume(name, specialization, templatePath string, focusSkills []string) *Resume {
	now := time.Now().UTC()
	return &Resume{
		ID:             uuid.New(),
		Name:           name,
		Specialization: specialization,
		TemplatePath:   templatePath,
		FocusSkills:    focusSkills,
		Content:        ResumeContentDB{}, // Empty content
		Version:        1,
		CreatedAt:      now,
		UpdatedAt:      now,
	}
}

// ResumeVersion represents a versioned snapshot of resume content.
type ResumeVersion struct {
	ID        uuid.UUID       `db:"id"`
	ResumeID  uuid.UUID       `db:"resume_id"`
	Content   ResumeContentDB `db:"content"`
	Version   int32           `db:"version"`
	PdfKey    *string         `db:"pdf_key"`
	CreatedAt time.Time       `db:"created_at"`
}

// CoverLetter represents a generated cover letter with LLM traceability.
type CoverLetter struct {
	ID            uuid.UUID      `db:"id"`
	JobID         *uuid.UUID     `db:"job_id"`
	ResumeID      *uuid.UUID     `db:"resume_id"`
	JobTitle      *string        `db:"job_title"`      // denormalized job title for quick display
	Content       string         `db:"content"`        // plain text cover letter content
	Model         *string        `db:"model"`          // LLM model used (e.g., "ollama/qwen2.5")
	PromptVersion *string        `db:"prompt_version"` // prompt version used for traceability
	ResumeVersion *int32         `db:"resume_version"` // resume version used for generation
	PdfKey        *string        `db:"pdf_key"`        // storage key for generated PDF
	Strengths     *StringSliceDB `db:"strengths"`      // LLM-identified strengths to highlight
	Gaps          *StringSliceDB `db:"gaps"`           // LLM-identified gaps to address
	WordCount     *int           `db:"word_count"`
	Version       int32          `db:"version"`
	CreatedAt     time.Time      `db:"created_at"`
	UpdatedAt     time.Time      `db:"updated_at"`
}

// CoverLetterVersion represents a versioned snapshot of cover letter content.
type CoverLetterVersion struct {
	ID            uuid.UUID `db:"id"`
	CoverLetterID uuid.UUID `db:"cover_letter_id"`
	Content       string    `db:"content"`
	Version       int32     `db:"version"`
	Model         *string   `db:"model"`
	PromptVersion *string   `db:"prompt_version"`
	ResumeVersion *int32    `db:"resume_version"`
	CreatedAt     time.Time `db:"created_at"`
}

// NewCoverLetter creates a new CoverLetter with default values.
func NewCoverLetter() *CoverLetter {
	now := time.Now().UTC()
	return &CoverLetter{
		ID:        uuid.New(),
		Version:   1,
		CreatedAt: now,
		UpdatedAt: now,
	}
}

// Domain errors for resumes.
var (
	ErrInvalidInput    = errors.New("invalid input")
	ErrNotFound        = errors.New("resume not found")
	ErrNoContent       = errors.New("resume has no content")
	ErrVersionConflict = errors.New("version conflict — resource was modified by another process")
)
