apiVersion: v1
kind: Service
metadata:
  name: myjob-api
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: Service
metadata:
  name: myjob-browser-agent
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: browser-agent
---
apiVersion: v1
kind: Service
metadata:
  name: myjob-frontend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: myjob-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/component: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: myjob-redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/component: redis
