/**
 * Resume and Cover Letter types — aligned with backend/internal/resumes/dto.go.
 *
 * Covers:
 * - Resume (list + detail views)
 * - ResumeContent (structured LLM-generated content)
 * - CoverLetter
 * - ResumeVersion (historical snapshots)
 */

/** Structured resume content generated by LLM. */
export interface ResumeContent {
  summary: string;
  skills: string[];
  experience: ExperienceEntry[];
  projects: ProjectEntry[];
  education: EducationEntry[];
  certifications: string[];
  languages: LanguageEntry[];
  links: LinkEntry[];
}

/** Work experience entry. */
export interface ExperienceEntry {
  title: string;
  company: string;
  location: string;
  start_date: string;
  end_date: string;
  description: string;
  skills_used: string[];
  highlights: string[];
}

/** Project entry. */
export interface ProjectEntry {
  name: string;
  description: string;
  technologies: string[];
  link?: string;
  start_date?: string;
  end_date?: string;
}

/** Education entry. */
export interface EducationEntry {
  institution: string;
  degree: string;
  field: string;
  start_date: string;
  end_date: string;
  gpa?: string;
  honors?: string[];
}

/** Language proficiency entry. */
export interface LanguageEntry {
  language: string;
  proficiency: string;
}

/** Link entry (GitHub, LinkedIn, portfolio). */
export interface LinkEntry {
  type: string;
  url: string;
  label?: string;
}

/** Resume — list view (content omitted). */
export interface Resume {
  id: string;
  name: string;
  specialization: string;
  template_path: string;
  focus_skills: string[];
  highlight_experience?: string[];
  has_content: boolean;
  pdf_key?: string;
  version: number;
  created_at: string;
  updated_at: string;
}

/** Resume — detail view (includes content). */
export interface ResumeDetail extends Resume {
  content?: ResumeContent;
}

/** Cover letter — list + detail view. */
export interface CoverLetter {
  id: string;
  job_id?: string;
  resume_id?: string;
  job_title?: string;
  content: string;
  model?: string;
  prompt_version?: string;
  resume_version?: number;
  strengths?: string[];
  gaps?: string[];
  pdf_key?: string;
  word_count?: number;
  version: number;
  created_at: string;
  updated_at: string;
}

/** Resume version — historical snapshot. */
export interface ResumeVersion {
  id: string;
  resume_id: string;
  version: number;
  content: ResumeContent;
  pdf_key?: string;
  created_at: string;
}

/** List response for resumes. */
export interface ResumeListResponse {
  resumes: Resume[];
  total: number;
  limit: number;
  offset: number;
}

/** List response for cover letters. */
export interface CoverLetterListResponse {
  cover_letters: CoverLetter[];
  total: number;
  limit: number;
  offset: number;
}

/** List response for resume versions. */
export interface ResumeVersionListResponse {
  versions: ResumeVersion[];
}

/** Content response for resume content operations. */
export interface ResumeContentResponse {
  resume_id: string;
  version: number;
  content: ResumeContent;
}

/** Create resume request. */
export interface CreateResumeRequest {
  name: string;
  specialization: string;
  template_path: string;
  focus_skills: string[];
  highlight_experience?: string[];
}

/** Update resume request. */
export interface UpdateResumeRequest {
  name: string;
  specialization: string;
  template_path: string;
  focus_skills: string[];
  highlight_experience?: string[];
}

/** Generate resume content request. */
export interface GenerateResumeContentRequest {
  job_id?: string;
  job_title?: string;
  job_requirements?: string;
}

/** Update resume content request. */
export interface UpdateResumeContentRequest {
  content: ResumeContent;
}

/** Create cover letter request. */
export interface CreateCoverLetterRequest {
  job_id: string;
  resume_id?: string;
}

/** Generate cover letter request. */
export interface GenerateCoverLetterRequest {
  job_title: string;
  job_requirements: string;
  job_description: string;
  resume_id?: string;
}

/** Update cover letter content request. */
export interface UpdateCoverLetterContentRequest {
  content: string;
}

/** List params for resumes. */
export interface ResumeListParams {
  limit?: number;
  offset?: number;
}

/** List params for cover letters. */
export interface CoverLetterListParams {
  limit?: number;
  offset?: number;
}
