$kind: http-request
name: Create Application
method: POST
url: '{{baseUrl}}/api/v1/applications'
order: 4000
headers:
  - key: Content-Type
    value: application/json
body:
  type: json
  content: |-
    {
      "job_id": "{{jobId}}",
      "resume_id": "{{resumeId}}",
      "cover_letter_id": null,
      "portal_type": "greenhouse",
      "portal_url": "https://..."
    }
