$kind: http-request
name: Update Application Status
method: PUT
url: '{{baseUrl}}/api/v1/applications/{{applicationId}}/status'
order: 5000
pathVariables:
  - key: applicationId
    value: '{{applicationId}}'
headers:
  - key: Content-Type
    value: application/json
body:
  type: json
  content: |-
    {
      "status": "applied",
      "notes": "Applied via portal"
    }
