$kind: http-request
name: Test Email Config
method: POST
url: '{{baseUrl}}/api/v1/auth/setup/test-email'
order: 5000
auth:
  type: noauth
headers:
  - key: Content-Type
    value: application/json
body:
  type: json
  content: |-
    {
      "tenant_id": "your_tenant_id",
      "client_id": "your_client_id",
      "client_secret": "your_secret"
    }
