{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: monitoring
  labels:
    {{- include "myjob.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.monitoring.grafana.adminPassword | b64enc | quote }}
{{- end }}
